global:
  scrape_interval: 15s

# мониторинг хоста
scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets:
        - "node-exporter:9100"

  - job_name: "nmnh_app"
    static_configs:
      - targets:
        - "web:8000"
